"""W3 · the inbound webhook receiver (SPEC §5).

A tiny HTTP front door, deployed alongside the worker. AgentMail POSTs a
Svix-signed event here when an email arrives; this app verifies the signature
(proving the request really came from AgentMail — the ``signature_verified``
provenance check, SPEC §0.6), maps the message onto the domain
``InboundMessage``, and starts a ``DispatchWorkflow`` on Temporal. The
*dispatcher* then does the routing (reply / receipt / command / quarantine);
this only authenticates the transport and hands off.

AgentMail already authenticates the *sender* (SPF/DKIM/DMARC) and surfaces it as
the event type, so only ``message.received`` is acted on — ``*.unauthenticated``
/ ``*.spam`` / ``*.blocked`` are ignored here. The Temporal client lives on
``app.state`` so tests inject one without a real connection.
"""

from __future__ import annotations

import html
import os
import re
from contextlib import asynccontextmanager
from typing import TYPE_CHECKING

from fastapi import FastAPI, HTTPException, Request
from pydantic import BaseModel, ConfigDict, Field

from ynab_agent.dispatch.classify import InboundMessage
from ynab_agent.domain.ids import MessageId, ThreadId
from ynab_agent.workflow.dispatch_types import DispatchParams
from ynab_agent.workflow.dispatch_workflow import DispatchWorkflow

if TYPE_CHECKING:
    from collections.abc import AsyncIterator, Mapping

    from temporalio.client import Client

WEBHOOK_SECRET_ENV = "AGENTMAIL_WEBHOOK_SECRET"
_RECEIVED = "message.received"


class _WireMessage(BaseModel):
    """The message fields we read from an AgentMail webhook (loose)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    message_id: str
    from_address: str = Field(alias="from")
    subject: str = ""
    text: str | None = None
    # The new reply text with the quoted history stripped — what the human
    # actually wrote. Preferred over ``text`` so the interpreter isn't fed the
    # whole quoted proposal back.
    extracted_text: str | None = None
    # The HTML part — the salvage path for HTML-only replies (Apple Mail
    # sends these), whose text parts arrive empty.
    html: str | None = None
    thread_id: str | None = None
    # The raw RFC 822 headers AgentMail surfaces (a flat name→value dict). Read
    # only to detect machine-generated mail (see ``_is_auto_reply``); ``None``
    # when AgentMail omits them.
    headers: dict[str, str] | None = None


class _WebhookPayload(BaseModel):
    """An AgentMail webhook event — only the parts we use.

    The Svix envelope's top-level ``type`` is always the literal ``"event"``;
    the actual event name (``message.received`` and its ``.spam`` / ``.blocked``
    / ``.unauthenticated`` variants) is in ``event_type``. We act only on an
    exact ``message.received``.
    """

    model_config = ConfigDict(extra="ignore")

    event_type: str = ""
    message: _WireMessage | None = None


# RFC 3834 + de-facto vendor markers that a message was generated by a machine
# (a vacation/auto-reply, a bounce, or a bulk mailer) rather than typed by a
# human. Such a message must never be read as a confirmation — "silence is not
# consent" (SPEC §0.6 inbound boundary, §5d).
_AUTO_PRECEDENCE = frozenset({"bulk", "auto_reply", "junk"})
_AUTO_MARKER_HEADERS = ("x-autoreply", "x-autorespond", "list-id")


def _is_auto_reply(headers: Mapping[str, str] | None) -> bool:
    """True if the inbound headers mark the message as machine-generated.

    Per RFC 3834, ``Auto-Submitted`` present and set to anything but ``no``
    means the message was produced automatically (the canonical vacation /
    auto-reply signal). We also honor the de-facto ``Precedence:
    bulk/auto_reply/junk`` convention and the vendor ``X-Autoreply`` /
    ``X-Autorespond`` markers, plus ``List-Id`` (bulk/list traffic). Header
    names are case-insensitive, so the lookup is normalized to lower case.
    """
    if not headers:
        return False
    lowered = {
        name.lower(): value.strip().lower() for name, value in headers.items()
    }
    auto_submitted = lowered.get("auto-submitted")
    if auto_submitted is not None and auto_submitted != "no":
        return True
    if lowered.get("precedence") in _AUTO_PRECEDENCE:
        return True
    return any(header in lowered for header in _AUTO_MARKER_HEADERS)


_HTML_BREAKS = re.compile(r"(?i)<br\s*/?>|</p>|</div>|</blockquote>|</tr>")
_HTML_TAGS = re.compile(r"<[^>]+>")
_HTML_INVISIBLE = re.compile(r"(?is)<(style|script|head)[^>]*>.*?</\1>")
# A forward's preamble (Apple Mail / Gmail / Outlook) — when the words before
# the first blockquote are just this, the content IS the blockquote.
_FORWARD_MARKER = re.compile(r"(?i)forwarded message|original message")


def _plain_text(fragment: str) -> str:
    """An HTML fragment reduced to readable lines."""
    fragment = _HTML_INVISIBLE.sub(" ", fragment)
    text = _HTML_TAGS.sub(" ", _HTML_BREAKS.sub("\n", fragment))
    lines = (line.strip() for line in html.unescape(text).splitlines())
    return "\n".join(line for line in lines if line).strip()


def _text_from_html(html_part: str | None) -> str:
    """Plain text salvaged from an HTML-only message.

    Apple Mail sends both replies and forwards with empty text parts and the
    words only in HTML. The two need opposite treatment: a REPLY's new words
    come before the first ``<blockquote>`` (the quoted history below is
    dropped, mirroring AgentMail's ``extracted_text``), while a FORWARD's
    whole content — the receipt — lives *inside* the blockquote, with only a
    "Begin forwarded message:" preamble above it. A forward-marker (or
    empty) preamble therefore salvages the entire document.
    """
    if not html_part:
        return ""
    head = re.split(r"(?i)<blockquote", html_part, maxsplit=1)[0]
    head_text = _plain_text(head)
    if not head_text or _FORWARD_MARKER.search(head_text):
        return _plain_text(html_part)
    return head_text


def to_inbound(message: _WireMessage, *, verified: bool) -> InboundMessage:
    """Map a verified webhook message onto the domain InboundMessage."""
    body = (
        message.extracted_text or message.text or _text_from_html(message.html)
    )
    return InboundMessage(
        message_id=MessageId(message.message_id),
        from_address=message.from_address,
        subject=message.subject,
        body=body,
        thread_id=ThreadId(message.thread_id) if message.thread_id else None,
        signature_verified=verified,
        is_auto_reply=_is_auto_reply(message.headers),
    )


def verify(body: bytes, headers: Mapping[str, str], secret: str) -> object:
    """Verify an AgentMail (Svix) webhook and return its parsed payload.

    Raises ``svix.webhooks.WebhookVerificationError`` if the signature is bad.
    """
    from svix.webhooks import Webhook

    return Webhook(secret).verify(body, dict(headers))


async def start_dispatch(
    client: Client,
    inbound: InboundMessage,
    *,
    allowlist: frozenset[str],
    task_queue: str,
) -> bool:
    """Start a DispatchWorkflow for one message; idempotent (SPEC §5).

    The workflow id is derived from the message id, and the id-reuse policy
    rejects duplicates (running *or* completed), so an AgentMail webhook retry
    is a no-op rather than a re-dispatch. Returns ``True`` if newly started,
    ``False`` if it had already been dispatched.
    """
    from temporalio.common import WorkflowIDReusePolicy
    from temporalio.exceptions import WorkflowAlreadyStartedError

    try:
        await client.start_workflow(
            DispatchWorkflow.run,
            DispatchParams(message=inbound, allowlist=allowlist),
            id=f"dispatch-{inbound.message_id}",
            task_queue=task_queue,
            id_reuse_policy=WorkflowIDReusePolicy.REJECT_DUPLICATE,
        )
    except WorkflowAlreadyStartedError:
        return False
    return True


def _allowlist_from_env() -> frozenset[str]:
    """Who may act by email: the owners plus their extra sender addresses.

    ``allowed_senders`` covers an owner's secondary address (an iCloud alias
    forwarding receipts) — allow-listed to act, but never mailed.
    """
    from ynab_agent.settings import Settings

    settings = Settings()
    return frozenset(
        address.lower()
        for address in (*settings.owners, *settings.allowed_senders)
    )


async def _connect() -> Client:
    from temporalio.client import Client
    from temporalio.contrib.pydantic import pydantic_data_converter

    from ynab_agent.telemetry import metrics_runtime, tracing_interceptors

    return await Client.connect(
        os.environ.get("TEMPORAL_HOST", "localhost:7233"),
        namespace=os.environ.get("TEMPORAL_NAMESPACE", "default"),
        data_converter=pydantic_data_converter,
        interceptors=tracing_interceptors(),
        runtime=metrics_runtime(),
    )


def create_app(
    *,
    webhook_secret: str | None = None,
    allowlist: frozenset[str] | None = None,
    task_queue: str | None = None,
) -> FastAPI:
    """Build the webhook app.

    Production reads its config from the environment; tests pass it in and set
    ``app.state.temporal`` before startup.
    """
    secret = (
        webhook_secret
        if webhook_secret is not None
        else os.environ.get(WEBHOOK_SECRET_ENV)
    )
    queue = task_queue or os.environ.get("TEMPORAL_TASK_QUEUE", "ynab-agent")
    allow = allowlist if allowlist is not None else _allowlist_from_env()

    @asynccontextmanager
    async def lifespan(app: FastAPI) -> AsyncIterator[None]:
        if not hasattr(app.state, "temporal"):
            app.state.temporal = await _connect()
        yield
        # uvicorn fires this on SIGTERM; flush buffered spans before exit.
        from ynab_agent.telemetry import shutdown_tracing

        shutdown_tracing()

    app = FastAPI(lifespan=lifespan, title="ynab-agent webhook")

    from ynab_agent.telemetry import instrument_fastapi, setup_tracing

    setup_tracing("ynab-agent-webhook")
    instrument_fastapi(app)

    @app.get("/healthz")
    async def healthz() -> dict[str, str]:
        return {"status": "ok"}

    @app.post("/webhooks/agentmail")
    async def agentmail_webhook(request: Request) -> dict[str, str]:
        if not secret:
            raise HTTPException(
                status_code=500, detail="webhook secret not configured"
            )
        body = await request.body()
        from svix.webhooks import WebhookVerificationError

        try:
            payload = verify(body, request.headers, secret)
        except WebhookVerificationError as err:
            raise HTTPException(
                status_code=401, detail="invalid signature"
            ) from err

        event = _WebhookPayload.model_validate(payload)
        if event.event_type != _RECEIVED or event.message is None:
            return {"status": "ignored"}

        inbound = to_inbound(event.message, verified=True)
        started = await start_dispatch(
            request.app.state.temporal,
            inbound,
            allowlist=allow,
            task_queue=queue,
        )
        return {"status": "dispatched" if started else "duplicate"}

    return app
